In [1]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2
# 多行输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 

In [2]:
import numpy as np
from tqdm import trange, tqdm, tqdm_notebook
import scipy.io as sio
from kalman_estimation import Selector, get_mat_data

- matlab 代码
```matlab
f_name = [data_root, 'FROLS_', int2str(ndim), flag, '_est100_', sprintf('%2.2f', err_var), '.mat'];
save(f_name, 'coef_est100', 'terms_chosen100', 'ERRs100', 'mean_coef', 'var_coef');
```

In [3]:
con_terms_linear5 = ['x1(t-1)', 'x1(t-2)', 'x1(t-2)', 'x1(t-3)', 'x1(t-2)', 'x4(t-1)', 'x5(t-1)', 'x4(t-1)', 'x5(t-1)']  # 9
con_terms_nonlinear5 = ['x1(t-1)', 'x1(t-2)', 'x1(t-2)*x1(t-2)', 'x1(t-3)', 'x1(t-2)*x1(t-2)', 'x4(t-1)', 'x5(t-1)', 'x4(t-1)', 'x5(t-1)']  # 9
true_coefs5 = [0.95*np.sqrt(2), -0.9025, 0.5, -0.4, -0.5, 0.25*np.sqrt(2), 0.25*np.sqrt(2), -0.25*np.sqrt(2), 0.25*np.sqrt(2)]  # 9
con_terms_linear10 = ['x1(t-1)', 'x1(t-2)', 'x1(t-2)', 'x2(t-3)', 'x1(t-2)', 'x4(t-4)', 'x9(t-2)', 'x4(t-4)', 'x1(t-1)', 'x1(t-2)', 'x7(t-2)', 
                      'x8(t-3)', 'x9(t-3)', 'x8(t-3)', 'x9(t-3)', 'x7(t-4)']  # 16
con_terms_nonlinear10 = ['x1(t-1)', 'x1(t-2)', 'x1(t-2)*x1(t-2)', 'x2(t-3)', 'x1(t-2)', 'x4(t-4)', 'x9(t-2)', 'x4(t-4)', 'x1(t-1)*x1(t-2)', 'x1(t-2)', 'x7(t-2)', 
                      'x8(t-3)', 'x9(t-3)', 'x8(t-3)', 'x9(t-3)', 'x7(t-4)']  # 16
true_coefs10 = [0.95*np.sqrt(2), -0.9025, 0.5, 0.9, -0.5, 0.8, -0.4, -0.8, 0.4, -0.4, -0.9, 0.4, 0.3, -0.3, 0.4, -0.75]  # 16
noises = np.linspace(0.5, 4, 8)
con_terms5 = [2, 1, 1, 3, 2]
con_terms10 = [2, 1, 1, 1, 2, 1, 2, 3, 2, 1]
root = '../data/'

In [4]:
def corr_term(y_coef, terms_set, Kalman_S_No, var_name: str = 'x', step_name: str = 't'):
    n_dim, n_term = y_coef.shape
    func_repr = []
    for var in range(n_dim):
        y = {}
        for term in range(n_term):
            y[terms_set[Kalman_S_No[var, term]]] = y_coef[var, term]
        func_repr.append(y)
    return func_repr

In [15]:
def frols(noise_var, ndim, dtype, terms, length, root='../data/', trials=100):
    assert dtype in ['linear', 'nonlinear'], 'type not support!'
    terms_path = root + f'FROLS_{ndim}{dtype}_est100_{noise_var:2.2f}.mat'
    terms_pathx = root + f'{dtype}_terms{ndim}D_0.50trial1.mat'
    term = Selector(terms_pathx)
    candidate_terms = term.make_terms()
    y_coef = get_mat_data(terms_path, 'coef_est100')
    Kalman_S_No = get_mat_data(terms_path, 'terms_chosen100')
    flatten_coef = []
    for trial in trange(trials):
        ax, t, S_No = [], 0, Kalman_S_No[trial] - 1
        for i in range(ndim):
            terms_set = corr_term(y_coef[trial], candidate_terms, S_No)
            tmp = []
            for k in terms[t:t+length[i]]:
                tmp.append(terms_set[i][k] if k in terms_set[i] else np.nan)
            ax.extend(tmp)
            t += length[i]
        flatten_coef.append(ax)
    return np.stack(flatten_coef)

In [16]:
terms_pathx = root + f'linear_terms5D_0.50trial1.mat'
term = Selector(terms_pathx)
candidate_terms = term.make_terms()

In [17]:
term_dict = {t:i for i, t in enumerate(candidate_terms)}

In [23]:
coef = frols(2.5, 5, 'nonlinear', con_terms_nonlinear5, con_terms5, trials=1)
coef

100%|██████████| 1/1 [00:00<00:00, 806.13it/s]


array([[ 1.34590727, -0.90030045,  0.50116825, -0.40483858, -0.5013467 ,
         0.34502312,  0.3390138 , -0.35082569,  0.36173356]])

In [19]:
coef.shape

(1, 9)

In [20]:
coef.var(0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
coef.mean(0)

array([ 1.34590727, -0.90030045,  0.50116825, -0.40483858, -0.5013467 ,
        0.34502312,  0.3390138 , -0.35082569,  0.36173356])